### ISSUE TITLE
[ISSUE] err-dashboard_helper_missing  The dashboard helper is unavailable for this user.

### ISSUE THREAD

**Issue by shtrom** [ccpk1/ChoreOps#191]
### Home Assistant version

2026.6.3 and 2026.6.4

### ChoreOps integration version

1.0.8-beta.2

### Installation method

HACS

### Prerequisites

- [x] I checked for existing open and closed issues
- [x] I updated ChoreOps (or confirmed the issue still occurs on the latest version)
- [x] If this is a dashboard issue, I updated dashboard dependencies such as button-card and confirmed the issue still occurs
- [x] I enabled debug logging and can share logs

### Issue scope

Dashboard UI/template

### Steps to reproduce

1. Install 1.0.8-beta.2 as a work around for #124  (also tested without Mushroom card 1.1.1/1.2.0 pre-release) 
2. Recreate the dashboards (either Standard, Essential or Lite)
3. Go to the dashboard
4. See two blocks with the same issues for all users
```
Cannot find: err-dashboard_helper_missing

The dashboard helper is unavailable for this user.
```

Similar for the admin dashboard: multiple cards with the same error:
```
⚠️ Admin Dashboard Helpers Not Found

The admin selector or shared admin helper entity could not be resolved for this dashboard context.
```

Deleting and re-creating the dashboard leads to the same issue.

### Issue description

After upgrade to 1.0.8-beta.2 to work around #124, none of the dashboards render anymore, with errors about missing templates.

### Logs

One error, though it looks unrelated.
```
2026-06-20 18:05:37.300 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up choreops platform for sensor: 'int' object has no attribute 'startswith'
  File "/config/custom_components/choreops/sensor.py", line 556, in async_setup_entry
  File "/config/custom_components/choreops/managers/ui_manager.py", line 281, in async_reconcile_chore_shards_for_users
  File "/config/custom_components/choreops/managers/ui_manager.py", line 401, in _get_existing_chore_shard_entries
```

The rest of the log seems pretty uneventful.

```
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager NotificationManager listening to event 'user_deleted' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] NotificationManager initialized with 18 event subscriptions for entry 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'stats_ready' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'stats_updated' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'points_changed' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'chore_approved' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'chore_disapproved' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'chore_status_reset' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'chore_overdue' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'reward_approved' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'bonus_applied' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'penalty_applied' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'midnight_rollover' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'user_deleted' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'chore_deleted' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager GamificationManager listening to event 'chore_updated' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] GamificationManager initialized with 2.0 second debounce
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'chores_ready' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'points_changed' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'chore_approved' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'chore_points_awarded' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'chore_completed' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.832 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'chore_claimed' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'chore_disapproved' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'chore_overdue' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'chore_missed' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'chore_status_reset' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'chore_undone' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'reward_approved' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'reward_claimed' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'reward_disapproved' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'badge_earned' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'bonus_applied' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'penalty_applied' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'midnight_rollover' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'periodic_update' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'chore_data_reset_complete' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'points_data_reset_complete' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'badge_data_reset_complete' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'achievement_data_reset_complete' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'challenge_data_reset_complete' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'reward_data_reset_complete' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'penalty_data_reset_complete' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager StatisticsManager listening to event 'bonus_data_reset_complete' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] StatisticsManager: Event subscriptions initialized
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager SystemManager listening to event 'user_deleted' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager SystemManager listening to event 'chore_deleted' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager SystemManager listening to event 'reward_deleted' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] Manager SystemManager listening to event 'badge_deleted' for instance 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] SystemManager: Midnight catch-up not needed (last_processed=2026-06-19T14:00:00.288140+00:00)
2026-06-20 18:05:34.833 DEBUG (MainThread) [custom_components.choreops] SystemManager initialized: timer registered, 4 DELETED signal subscriptions for entry 01KKX0TB7X31B33KPGE76GK3CF
2026-06-20 18:05:34.870 INFO (MainThread) [custom_components.choreops] ChoreOps services have been registered successfully
2026-06-20 18:05:37.165 DEBUG (MainThread) [custom_components.choreops] DEBUG: Button - PointsAdjustValue - Using adjustment deltas: [1.0, -1.0, 2.0, -2.0, 10.0, -10.0]
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Wren' with delta 1.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Wren' with delta -1.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Wren' with delta 2.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Wren' with delta -2.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Wren' with delta 10.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Wren' with delta -10.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Tim' with delta 1.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Tim' with delta -1.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Tim' with delta 2.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Tim' with delta -2.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Tim' with delta 10.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Tim' with delta -10.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Olivier' with delta 1.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Olivier' with delta -1.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Olivier' with delta 2.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Olivier' with delta -2.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Olivier' with delta 10.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Olivier' with delta -10.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Jen' with delta 1.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Jen' with delta -1.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Jen' with delta 2.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Jen' with delta -2.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Jen' with delta 10.0
2026-06-20 18:05:37.166 DEBUG (MainThread) [custom_components.choreops] DEBUG: Creating ApproverPointsAdjustButton for Assignee 'Jen' with delta -10.0
2026-06-20 18:05:37.300 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up choreops platform for sensor: 'int' object has no attribute 'startswith'
  File "/config/custom_components/choreops/sensor.py", line 556, in async_setup_entry
  File "/config/custom_components/choreops/managers/ui_manager.py", line 281, in async_reconcile_chore_shards_for_users
  File "/config/custom_components/choreops/managers/ui_manager.py", line 401, in _get_existing_chore_shard_entries
2026-06-20 18:05:37.334 DEBUG (MainThread) [custom_components.choreops] Loaded en dashboard translations
2026-06-20 18:05:37.365 DEBUG (MainThread) [custom_components.choreops] Loaded en dashboard translations
2026-06-20 18:05:37.388 DEBUG (MainThread) [custom_components.choreops] Loaded en dashboard translations
2026-06-20 18:05:37.394 DEBUG (MainThread) [custom_components.choreops] Loaded en dashboard translations
2026-06-20 18:05:38.382 DEBUG (MainThread) [custom_components.choreops] PERF: remove_conditional_entities() scanned in 0.005s, removed 0 entities and 0 devices
2026-06-20 18:05:38.383 DEBUG (MainThread) [custom_components.choreops] PERF: orphan scan for assignee-chore entity: 708 checked in 0.001s, none removed
2026-06-20 18:05:38.384 DEBUG (MainThread) [custom_components.choreops] PERF: orphan scan for shared chore sensor: 54 checked in 0.000s, none removed
2026-06-20 18:05:38.384 DEBUG (MainThread) [custom_components.choreops] PERF: orphan scan for assignee calendar: 4 checked in 0.000s, none removed
2026-06-20 18:05:38.384 DEBUG (MainThread) [custom_components.choreops] PERF: orphan scan for assignee datetime helper: 4 checked in 0.000s, none removed
2026-06-20 18:05:38.385 DEBUG (MainThread) [custom_components.choreops] PERF: orphan scan for badge progress sensor: 0 checked in 0.000s, none removed
2026-06-20 18:05:38.385 DEBUG (MainThread) [custom_components.choreops] PERF: orphan scan for achievement progress sensor: 0 checked in 0.000s, none removed
2026-06-20 18:05:38.386 DEBUG (MainThread) [custom_components.choreops] PERF: orphan scan for challenge progress sensor: 0 checked in 0.002s, none removed
2026-06-20 18:05:38.387 DEBUG (MainThread) [custom_components.choreops] PERF: orphan scan for manual adjustment button: 24 checked in 0.000s, none removed
2026-06-20 18:05:38.387 DEBUG (MainThread) [custom_components.choreops] PERF: startup orphan cleanup completed in 0.005s, no orphans found
2026-06-20 18:05:38.388 INFO (MainThread) [custom_components.choreops] INFO: ChoreOps setup complete for entry: 01KKX0TB7X31B33KPGE76GK3CF
```

### Additional context

There's ~79 chores for the most loaded user.

**Comment by ccpk1** [comment]
Are you able to do a diagnostic download and post it here?

If not, maybe grab one of backup files from the choreops directory.  More detail can be found in the troubleshooting wiki if you need.

Also, if you already had 79 chores for a user I assume it had stopped working in an early version and this upgrade was to find a solution for that?  Can you give me a little more background?

Version 1.5.0 beta 3 is the newest version and should already bundle all known features and fixes, so you should go ahead and upgrade to that before we go further.

**Comment by shtrom** [comment]
I ran into the same issue as #124: too many chores making the dashboard not render for that user (only).

I tried 1.0.8-beta.2, which made all dashboards, even before recreation, complain of what seems to be a missing template helper. The OpsCentre page also complains, but the missing helper seems different.

I'm now on 1.5.0-beta.3 (though it reports as beta.1 in the Settings), but still see the same problem.

Diagnostics for that version attached.
-- 
Olivier Mehani ***@***.***>
Sent from my mobile, please excuse my brevity.
Please consider the environment before using AI on this email.

**Comment by ccpk1** [comment]
I don’t think the diagnostic file got attached to your last message.

**Comment by shtrom** [comment]
Yep, apparently, GitHub doesn't take attachments from emails.

Here it is:
[config_entry-choreops-01KKX0TB7X31B33KPGE76GK3CF-1.json](https://github.com/user-attachments/files/29168907/config_entry-choreops-01KKX0TB7X31B33KPGE76GK3CF-1.json)

**Comment by ccpk1** [comment]
Go ahead and update to beta 4, I believe it will take care of the issue.  Let me know.  Thanks for reporting.

**Comment by shtrom** [comment]
It did! Thanks!

What was the problem?
-- 
Olivier Mehani ***@***.***>
Sent from my mobile, please excuse my brevity.
Please consider the environment before using AI on this email.

**Comment by ccpk1** [comment]
For the larger groups of chores, it has to split out into different helper sensors due to home assistant size limitations. All of the logic was there so a reload would clear it up, but it wasn’t doing it dynamically every time the way it should
